#!/usr/bin/env bash

# Function to query DNS information for a subdomain
query_dns() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dig_output=$(dig +short $sub.$domain)
        record_type=$(dig $sub.$domain | awk '/^'${sub}'\.'${domain}'\./ {print $4}')
        echo "The subdomain $sub is a $record_type record and points to $dig_output"
    done
}

# Main script
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain=$1
subdomain=$2

query_dns "$domain" "$subdomain"
